#!/bin/sh
# ref: gist at https://gist.github.com/chadmaughan/5889802

# stash any unstaged changes
git stash -q --keep-index

# run the tests with the gradle wrapper
./gradlew spotlessCheck --full-stacktrace

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# if [[ $RESULT != 0 ]]; then
#       echo "Formatting violations detected! Please run ./gradlew spotlessApply to fix the formatting errors."
# fi

# return the './gradlew test' exit code
exit $RESULT
